# based on https://github.com/istio/istio/blob/release-1.24/manifests/profiles/demo.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
  values:
    profile: demo